@startuml


rectangle "Database" as DB
actor "Data Analyst" as DA

rectangle "Population Report System" {
  usecase UC1 as "Produce Country Report"
  usecase UC2 as "Produce City Report"
  usecase UC3 as "Produce Capital City Report"
  usecase UC4 as "Produce Language Report"
  usecase UC5 as "Produce Population Report"



}



' Relationships
DA --> UC1
DA --> UC2
DA --> UC3
DA --> UC4
DA --> UC5


UC1 --> DB
UC2 --> DB
UC3 --> DB
UC4 --> DB
UC5 --> DB

@enduml
